name: zlib-accel Build and Test (clang)
on:
- push
- pull_request
jobs:
  build_and_test_zlib_accel:
    name: Build and test zlib-accel
    runs-on: ubuntu-latest
    steps:
    - name: Print system info
      run: |
        echo "Kernel"
        uname -r
        echo "OS"
        cat /etc/os-release
        echo "Cores"
        nproc
        echo "Memory"
        free
        echo "User"
        whoami
    
    - name: Install dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get install -y build-essential
        sudo apt-get install -y clang
        sudo apt-get install -y cmake
        sudo apt-get install -y libgtest-dev
        sudo apt-get install -y zlib1g-dev
    
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Build zlib-accel
      run: |
        sudo apt-get install -y build-essential
        pwd
        mkdir build
        cd build
        cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
        make
        
    - name: Build tests
      run: |
        pwd
        cd tests
        mkdir build
        cd build
        cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
        make
        
    - name: Build fuzz tests
      run: |
        pwd
        cd fuzzing
        mkdir build
        cd build
        cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
        make
        
    - name: Run unit tests
      run: |
        pwd
        cd tests/build
        make run
    
